app = "wishlist-bot-yeswanth"
primary_region = "dfw"

[build]

[processes]
  worker = "python bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "wishlist_data"
  destination = "/data"
